/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateGenreArgs } from "./CreateGenreArgs";
import { UpdateGenreArgs } from "./UpdateGenreArgs";
import { DeleteGenreArgs } from "./DeleteGenreArgs";
import { GenreFindManyArgs } from "./GenreFindManyArgs";
import { GenreFindUniqueArgs } from "./GenreFindUniqueArgs";
import { Genre } from "./Genre";
import { BookFindManyArgs } from "../../book/base/BookFindManyArgs";
import { Book } from "../../book/base/Book";
import { GenreService } from "../genre.service";

@graphql.Resolver(() => Genre)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class GenreResolverBase {
  constructor(
    protected readonly service: GenreService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Genre",
    action: "read",
    possession: "any",
  })
  async _genresMeta(
    @graphql.Args() args: GenreFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Genre])
  @nestAccessControl.UseRoles({
    resource: "Genre",
    action: "read",
    possession: "any",
  })
  async genres(@graphql.Args() args: GenreFindManyArgs): Promise<Genre[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Genre, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Genre",
    action: "read",
    possession: "own",
  })
  async genre(
    @graphql.Args() args: GenreFindUniqueArgs
  ): Promise<Genre | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Genre)
  @nestAccessControl.UseRoles({
    resource: "Genre",
    action: "create",
    possession: "any",
  })
  async createGenre(@graphql.Args() args: CreateGenreArgs): Promise<Genre> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Genre)
  @nestAccessControl.UseRoles({
    resource: "Genre",
    action: "update",
    possession: "any",
  })
  async updateGenre(
    @graphql.Args() args: UpdateGenreArgs
  ): Promise<Genre | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Genre)
  @nestAccessControl.UseRoles({
    resource: "Genre",
    action: "delete",
    possession: "any",
  })
  async deleteGenre(
    @graphql.Args() args: DeleteGenreArgs
  ): Promise<Genre | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Book])
  @nestAccessControl.UseRoles({
    resource: "Book",
    action: "read",
    possession: "any",
  })
  async books(
    @graphql.Parent() parent: Genre,
    @graphql.Args() args: BookFindManyArgs
  ): Promise<Book[]> {
    const results = await this.service.findBooks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
